name: ITech
version: 1.0
main: top.whitecola.itech.ITech
author: [White_cola]
depend:
  - HiPlugin
  - HolographicDisplays
  - EffectLib
api-version: 1.17
commands:
  itech:
    usage: /itech <command> [args] ...
permissions:
  itech.giveitem:
    default: op
  itech.example:
    default: op
  itech.uplevel:
    default: op
  itech.test:
    default: op
